### ISSUE TITLE
Can't cancel closing of Orchestra Example application

### ISSUE THREAD

**Issue by Aitania** [WildGums/Orchestra#60] opened 2017-01-14 20:48 UTC
Platform: Windows 7
.NET version: 4.6

### Expected behaviour
Possibility to prevent closing Orchestra Example Application

### Actual behaviour

If i close the application from [x] Button 

```
        protected override Task CloseAsync()
        {
             return base.CloseAsync();
        }
```

is called. Now is too late to stop shutdown. I want to ask user to save any changes.
I have tried a lot of events and the _navigationService.. Nothing helps.

From any other place like a fluent:BackstageTabItem its is possible with a CommandContainer

```
                    <fluent:Button x:Name="Exit"
                                   Command="{catel:CommandManagerBinding Application.Exit}"
                                   Header="Close"
                                   Icon="/Resources/Images/exit.png"
                                   KeyTip="X" />
```

**Comment by mkhomutov** [comment] 2017-01-14 20:59
try to use 'CloseApplicationWatcherBase' from Orchestra (you have to make your own implementation) and override `ClosingAsync()` method
then just return `false` if you don't want to close the app

**Comment by Aitania** [comment] 2017-01-15 13:51
I have solved with the closing event of MainWindow.
        private void MainWindow_Closing(object sender, System.ComponentModel.CancelEventArgs e)
        {
            var dependencyResolver = this.GetDependencyResolver();
            var _commandManager = dependencyResolver.Resolve<ICommandManager>();
            _commandManager.ExecuteCommand("Application.Exit");
            e.Cancel = true; // cancel it anyway... ApplicationExitCommandContainer will decide.. protected override async void Execute(object parameter) is async !
        }

**Comment by mkhomutov** [comment] 2017-01-15 19:29
actually `CloseApplicationWatcherBase` is doing the same internally
but in such case you don't need to make decision about closing the app inside of `ApplicationExitCommandContainer` 
the `ApplicationExitCommandContainer` will try to close the app anyway. But your application watcher class can make such decision (the class inherited from the `CloseApplicationWatcherBase`).

anyway, I think the problem is solved.

**Closed** 2017-01-15 20:25 UTC
