### ISSUE TITLE
TextBox validation error message displayed twice (in the MahApps example)

### ISSUE THREAD

**Issue by lipchev** [WildGums/Orchestra#405] opened 2020-09-08 21:23 UTC
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [x] .NET Core

## Component

What component is this issue occurring in?

Orchestra.Examples.MahApps

## Version of Library

Orchestra (6.0.4)

## Version of OS(s) listed above with issue

Win 10, .net core 3.1

## Steps to Reproduce
1. Click the Validation TextBox 

## Expected Behavior

Popup with just one validation error (as displayed in the info-bar) ?

## Actual Behavior
![image](https://user-images.githubusercontent.com/5253184/92528603-b6a7f000-f231-11ea-84b4-e67eb3f38d3a.png)

**Comment by GeertvanHorrik** [comment] 2020-09-09 07:22
@ceo1647 could this caused by our styles?

**Comment by ceo1647** [comment] 2020-09-17 18:12
it caused by ValidationViewModelBase, that implements both interfaces at the same time: IDataErrorInfo and INotifyDataErrorInfo...

**Comment by ceo1647** [comment] 2020-09-18 07:57
so to fix this behavior you need to enable only one validation strategy in a binding:
1) If you want to see only IDataErrorInfo validation errors Enable ValidateOnDataErrors and Disable ValidatesOnNotifyDataErrors explicitly (because default value is `true`) : `{Binding Text, ValidatesOnDataErrors=True, ValidatesOnNotifyDataErrors=False}`
2) If you want to see only INotifyDataErrorInfo -> it goes by default: (`"{Binding Text}"`)  
![image](https://user-images.githubusercontent.com/5163834/93571471-900e5580-f9a5-11ea-8c50-633d3b64a903.png)
It was fixed in hotfix 6.0.5...so you can view the changes

**Comment by ceo1647** [comment] 2020-09-18 08:02
Closing this ticket. Feel free to re-open if you think it's not fixed correctly

**Closed by ceo1647** 2020-09-18 08:02 UTC
