### ISSUE TITLE
Problem with Resources for MahApps in v5.1.7 (from 5.1.5)

### ISSUE THREAD

**Issue by lipchev** [WildGums/Orchestra#107] opened 2019-03-14 09:12 UTC
Hello,
the first symptom was an exception regarding the appbar_info icon not being found (i had it as part of the example code I had started with)- i just replaced with my own icon and forgot about it..
The second symptom however was harder to ignore- namely the disappearance of styles for the orc tab control.
Is there something I need to do in order to retain the original functionality (from version 5.1.5)?

PS I'm sorry I can't easily do a test with the examples from the repo as I'm running VS2017 (or is there some neat trick I'm not aware of?) 

Best regards,
Galin LIPCHEV

**Comment by GeertvanHorrik** [comment] 2019-03-15 11:41
Does this happen when consuming the libraries in your app, or when running the example apps?

**Comment by lipchev** [comment] 2019-03-15 13:45
No, it is the app that I'm working on- I haven't tested with the example as it targets .net core 3- but switching back and forth the nuget- there is clearly a difference. My app config is still pretty typical:

                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colors.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
                <ResourceDictionary Source="/Themes/Generic.xaml" />
...

**Comment by TruDan** [comment] 2019-03-17 19:02
I think my issue may be the same, 
![9zqI8CV](https://user-images.githubusercontent.com/983207/54496412-53b0f380-48ef-11e9-846e-a481498bc3ff.png)

Perhaps the Orchestra.Shell.MahApps\Resources\Icons.xaml should be defined in the project file? 

like so:
`<ItemGroup>
    <Page Include="Resources\Icons.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="Resources\IconsNonShared.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>`

**Comment by GeertvanHorrik** [comment] 2019-03-19 09:05
We will look into this and try to release a hotfix.

**Comment by GeertvanHorrik** [comment] 2019-03-19 09:36
This is caused by the explicit repository template props, it treats all files in /resources as resources. Will add a fix for this.

**Comment by GeertvanHorrik** [comment] 2019-03-19 09:39
5.1.8-beta0002 is being released right now. Could you please try that one before we release this hotfix?

**Comment by lipchev** [comment] 2019-03-19 11:14
For me the tab styles are fixed in 5.1.8-beta0002

**Comment by lipchev** [comment] 2019-03-19 11:19
Yep, WindowCommandHelper.CreateWindowCommandButton("appbar_information", "about") works as well (which I think is what TruDan was having a problem with)

**Comment by GeertvanHorrik** [comment] 2019-03-19 11:25
Thanks, will finalize now.

**Comment by lipchev** [comment] 2019-04-20 23:17
The same issues are back again in 5.2.0 (updating from 5.1.8)

**Comment by GeertvanHorrik** [comment] 2019-04-21 14:59
I'm afraid this is a regression because of the repository templates. Will try to fix asap.

**Comment by GeertvanHorrik** [comment] 2019-04-21 18:27
Please try Build - 5.2.1-beta.1

**Comment by lipchev** [comment] 2019-04-21 20:41
Looks good. Thanks.

**Comment by GeertvanHorrik** [comment] 2019-04-22 05:26
Thanks for checking so fast, 5.2.1 being released right now.

**Closed** 2019-04-22 12:27 UTC
Labels: bug, pinned
