### ISSUE TITLE
duplicate view model instance in MahApps example

### ISSUE THREAD

**Issue by askdong** [WildGums/Orchestra#44] opened 2016-02-15 12:24 UTC
If you open and close "about" dialog many times (for example 3 times), you will get below log:

> 20:14:38:005 => [DEBUG] [Catel.MVVM.ManagedViewModel] [1] Added view model instance, currently containing '3' instances of type 'Orchestra.ViewModels.AboutViewModel'

There will be **3** instances of AboutViewModel, it will cause memory leak.  

There is also same problem for "show dialog window" dialog

> 20:19:21:944 => [DEBUG] [Catel.MVVM.ManagedViewModel] [12] Added view model instance, currently containing '4' instances of type 'Orchestra.Examples.MahApps.ViewModels.ExampleDialogViewModel'

[Uploading Orchestra.Examples.MahApps_2016-02-15_201425_17792.txt…]()

**Comment by GeertvanHorrik** [comment] 2016-02-15 12:24
Thanks for reporting, will look into this.

**Comment by GeertvanHorrik** [comment] 2016-02-15 20:59
I can see this in the log as well. Might be caused by Catel, checking the combination now.

**Comment by GeertvanHorrik** [comment] 2016-02-15 21:21
Looks like the events in MahApps are differently for the ContentDialog. It's Unloaded => Closed instead of Closed => Unloaded (which the WPF Window does). Checking if I can find the cause and send a PR.

**Comment by GeertvanHorrik** [comment] 2016-02-15 21:23
No, it seems the ContentDialog doesn't even have a Closed event, I need to handle the Unloaded event a bit different.

**Comment by GeertvanHorrik** [comment] 2016-02-15 21:36
Fixed in Catel 4.5 prerelease.

**Closed** 2016-02-15 21:37 UTC

**Comment by askdong** [comment] 2016-02-16 05:46
awesome, thanks for your quick fix!
